export type AdditiveRisk = "HAZARDOUS" | "CAUTION" | "SAFE";

export interface AdditiveInfo {
    code: string;
    name: string;
    nameTr: string;
    risk: AdditiveRisk;
    reason: string;
    reasonTr: string;
    euStatus: "BANNED" | "RESTRICTED" | "ALLOWED";
    fdaStatus: "BANNED" | "WARNING" | "GRAS";
    category: "colorant" | "preservative" | "antioxidant" | "sweetener" | "emulsifier" | "thickener" | "acidity_regulator" | "flavor_enhancer" | "raising_agent" | "glazing_agent" | "other";
    categoryTr: string;
}

export const ADDITIVE_DATABASE: Record<string, AdditiveInfo> = {
    // HAZARDOUS - TEHLİKELİ

    E171: {
        code: "E171",
        name: "Titanium Dioxide",
        nameTr: "Titanyum Dioksit",
        risk: "HAZARDOUS",
        reason: "Titanium Dioxide is a white colorant that has been banned in the EU since 2022 due to concerns about DNA damage and potential carcinogenic effects. Nanoparticles can accumulate in organs and cross the blood-brain barrier. Studies have shown genotoxic effects in intestinal cells.",
        reasonTr:
            "Titanyum Dioksit, 2022'den bu yana AB'de yasaklanan beyaz bir renklendiricidir. DNA hasarı ve potansiyel kanserojen etkileri nedeniyle endişe yaratmaktadır. Nanopartiküller organlarda birikebilir ve kan-beyin bariyerini geçebilir. Çalışmalar bağırsak hücrelerinde genotoksik etkiler göstermiştir.",
        euStatus: "BANNED",
        fdaStatus: "GRAS",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E249: {
        code: "E249",
        name: "Potassium Nitrite",
        nameTr: "Potasyum Nitrit",
        risk: "HAZARDOUS",
        reason: "Potassium Nitrite is used as a preservative in processed meats. When heated or combined with amino acids, it can form nitrosamines, which are potent carcinogens linked to colorectal and stomach cancer. The WHO classifies processed meats as Group 1 carcinogens partly due to nitrites.",
        reasonTr:
            "Potasyum Nitrit, işlenmiş etlerde koruyucu olarak kullanılır. Isıtıldığında veya amino asitlerle birleştiğinde, kolorektal ve mide kanseriyle bağlantılı güçlü kanserojenler olan nitrozaminler oluşturabilir. WHO, kısmen nitritler nedeniyle işlenmiş etleri Grup 1 kanserojen olarak sınıflandırmaktadır.",
        euStatus: "RESTRICTED",
        fdaStatus: "WARNING",
        category: "preservative",
        categoryTr: "Koruyucu",
    },
    E250: {
        code: "E250",
        name: "Sodium Nitrite",
        nameTr: "Sodyum Nitrit",
        risk: "HAZARDOUS",
        reason: "Sodium Nitrite is the most common nitrite preservative in cured meats like bacon, ham, and hot dogs. It gives meat its pink color and prevents bacterial growth. However, it forms carcinogenic nitrosamines during high-heat cooking. Regular consumption of foods containing sodium nitrite is associated with increased cancer risk.",
        reasonTr:
            "Sodyum Nitrit, pastırma, jambon ve sosisli sandviç gibi kürlenmış etlerde en yaygın kullanılan nitrit koruyucusudur. Ete pembe rengini verir ve bakteri üremesini önler. Ancak yüksek ısıda pişirme sırasında kanserojen nitrozaminler oluşturur. Sodyum nitrit içeren gıdaların düzenli tüketimi artan kanser riskiyle ilişkilendirilmektedir.",
        euStatus: "RESTRICTED",
        fdaStatus: "WARNING",
        category: "preservative",
        categoryTr: "Koruyucu",
    },
    E251: {
        code: "E251",
        name: "Sodium Nitrate",
        nameTr: "Sodyum Nitrat",
        risk: "HAZARDOUS",
        reason: "Sodium Nitrate converts to sodium nitrite in the body and subsequently forms nitrosamines. It's commonly found in cured and processed meats. Long-term consumption has been linked to increased risk of colorectal cancer, pancreatic cancer, and cardiovascular issues due to its effect on blood vessels.",
        reasonTr:
            "Sodyum Nitrat, vücutta sodyum nitrite dönüşür ve ardından nitrozaminler oluşturur. Yaygın olarak kürlenmış ve işlenmiş etlerde bulunur. Uzun süreli tüketim, kan damarları üzerindeki etkisi nedeniyle kolorektal kanser, pankreas kanseri ve kardiyovasküler sorunlar riskinin artmasıyla ilişkilendirilmiştir.",
        euStatus: "RESTRICTED",
        fdaStatus: "WARNING",
        category: "preservative",
        categoryTr: "Koruyucu",
    },
    E252: {
        code: "E252",
        name: "Potassium Nitrate",
        nameTr: "Potasyum Nitrat",
        risk: "HAZARDOUS",
        reason: "Potassium Nitrate, also known as saltpeter, has been used for centuries in meat preservation. Like other nitrates, it converts to nitrite and then potentially to carcinogenic nitrosamines. It can also affect oxygen transport in blood and is particularly concerning for infants and people with certain health conditions.",
        reasonTr:
            "Güherçile olarak da bilinen Potasyum Nitrat, yüzyıllardır et muhafazasında kullanılmaktadır. Diğer nitratlar gibi nitrite, ardından potansiyel olarak kanserojen nitrozaminlere dönüşür. Ayrıca kanda oksijen taşınmasını etkileyebilir ve özellikle bebekler ve belirli sağlık sorunları olan kişiler için endişe vericidir.",
        euStatus: "RESTRICTED",
        fdaStatus: "WARNING",
        category: "preservative",
        categoryTr: "Koruyucu",
    },
    E127: {
        code: "E127",
        name: "Erythrosine (Red 3)",
        nameTr: "Eritrosin (Kırmızı 3)",
        risk: "HAZARDOUS",
        reason: "Erythrosine is a cherry-red synthetic dye that has been shown to cause thyroid tumors in rats. The FDA banned it from cosmetics and externally applied drugs in 1990 but still allows it in food. It contains iodine and can interfere with thyroid function. Many countries have restricted or banned its use.",
        reasonTr:
            "Eritrosin, sıçanlarda tiroid tümörlerine neden olduğu gösterilen kiraz kırmızısı sentetik bir boyadır. FDA, 1990'da kozmetiklerde ve harici ilaçlarda yasaklamış ancak gıdalarda hala izin vermektedir. İyot içerir ve tiroid fonksiyonunu bozabilir. Birçok ülke kullanımını kısıtlamış veya yasaklamıştır.",
        euStatus: "RESTRICTED",
        fdaStatus: "WARNING",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E131: {
        code: "E131",
        name: "Patent Blue V",
        nameTr: "Patent Mavi V",
        risk: "HAZARDOUS",
        reason: "Patent Blue V is a synthetic blue dye that has been banned by the FDA due to concerns about allergic reactions, including anaphylaxis. It can cause skin rashes, breathing difficulties, and in rare cases, severe allergic shock. It's still permitted in the EU but must carry warning labels.",
        reasonTr:
            "Patent Mavi V, anafilaksi dahil alerjik reaksiyonlarla ilgili endişeler nedeniyle FDA tarafından yasaklanmış sentetik mavi bir boyadır. Cilt döküntülerine, nefes darlığına ve nadir durumlarda şiddetli alerjik şoka neden olabilir. AB'de hala izinlidir ancak uyarı etiketleri taşıması gerekmektedir.",
        euStatus: "ALLOWED",
        fdaStatus: "BANNED",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E143: {
        code: "E143",
        name: "Fast Green FCF",
        nameTr: "Hızlı Yeşil FCF",
        risk: "HAZARDOUS",
        reason: "Fast Green FCF is a turquoise synthetic dye banned in the European Union due to insufficient safety data and concerns about potential carcinogenic effects. Animal studies have raised concerns about tumor development. It remains permitted in the US where it's commonly used in candies and beverages.",
        reasonTr:
            "Hızlı Yeşil FCF, yetersiz güvenlik verileri ve potansiyel kanserojen etkilerle ilgili endişeler nedeniyle Avrupa Birliği'nde yasaklanmış turkuaz sentetik bir boyadır. Hayvan çalışmaları tümör gelişimi konusunda endişelere yol açmıştır. ABD'de izinlidir ve yaygın olarak şekerlemelerde ve içeceklerde kullanılmaktadır.",
        euStatus: "BANNED",
        fdaStatus: "GRAS",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E924: {
        code: "E924",
        name: "Potassium Bromate",
        nameTr: "Potasyum Bromat",
        risk: "HAZARDOUS",
        reason: "Potassium Bromate is a flour improver that has been classified as a possible human carcinogen (Group 2B) by the IARC. It's banned in the EU, UK, Canada, Brazil, and many other countries. It can cause kidney damage and has been linked to thyroid and kidney tumors in animal studies.",
        reasonTr:
            "Potasyum Bromat, IARC tarafından olası insan kanserojen (Grup 2B) olarak sınıflandırılmış bir un iyileştiricidir. AB, İngiltere, Kanada, Brezilya ve diğer birçok ülkede yasaklanmıştır. Böbrek hasarına neden olabilir ve hayvan çalışmalarında tiroid ve böbrek tümörleriyle ilişkilendirilmiştir.",
        euStatus: "BANNED",
        fdaStatus: "BANNED",
        category: "other",
        categoryTr: "Diğer",
    },
    E925: {
        code: "E925",
        name: "Chlorine",
        nameTr: "Klor",
        risk: "HAZARDOUS",
        reason: "Chlorine is used to bleach flour and kill bacteria, but it destroys vital nutrients including vitamin E and beta-carotene. It can form harmful chlorinated compounds. The EU has banned chlorine-treated flour since it considers the practice unnecessary and potentially harmful to nutritional value.",
        reasonTr:
            "Klor, unu ağartmak ve bakterileri öldürmek için kullanılır, ancak E vitamini ve beta-karoten dahil hayati besin maddelerini yok eder. Zararlı klorlu bileşikler oluşturabilir. AB, bu uygulamayı gereksiz ve besin değeri için potansiyel olarak zararlı gördüğünden klorla işlenmiş unu yasaklamıştır.",
        euStatus: "BANNED",
        fdaStatus: "GRAS",
        category: "other",
        categoryTr: "Diğer",
    },
    E926: {
        code: "E926",
        name: "Chlorine Dioxide",
        nameTr: "Klor Dioksit",
        risk: "HAZARDOUS",
        reason: "Chlorine Dioxide is a powerful oxidizing agent used to bleach flour and treat water. It destroys vitamins, particularly vitamin E, and essential fatty acids. While less harmful than chlorine gas, it still raises concerns about nutrient loss and the formation of potentially harmful byproducts.",
        reasonTr:
            "Klor Dioksit, unu ağartmak ve suyu arıtmak için kullanılan güçlü bir oksitleyici ajandır. Vitaminleri, özellikle E vitaminini ve esansiyel yağ asitlerini yok eder. Klor gazından daha az zararlı olsa da, besin kaybı ve potansiyel olarak zararlı yan ürünlerin oluşumu konusunda endişelere yol açmaktadır.",
        euStatus: "RESTRICTED",
        fdaStatus: "GRAS",
        category: "other",
        categoryTr: "Diğer",
    },

    // CAUTION - DİKKATLİ TÜKETİLMELİ

    E102: {
        code: "E102",
        name: "Tartrazine (Yellow 5)",
        nameTr: "Tartrazin (Sarı 5)",
        risk: "CAUTION",
        reason: "Tartrazine is a bright yellow synthetic dye linked to hyperactivity in children, particularly those with ADHD. It can trigger allergic reactions, especially in aspirin-sensitive individuals. The EU requires warning labels stating it 'may have an adverse effect on activity and attention in children.'",
        reasonTr:
            "Tartrazin, özellikle DEHB'li çocuklarda hiperaktivite ile ilişkilendirilen parlak sarı sentetik bir boyadır. Özellikle aspirine duyarlı bireylerde alerjik reaksiyonları tetikleyebilir. AB, 'çocuklarda aktivite ve dikkat üzerinde olumsuz etkisi olabilir' şeklinde uyarı etiketleri gerektirir.",
        euStatus: "RESTRICTED",
        fdaStatus: "GRAS",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E104: {
        code: "E104",
        name: "Quinoline Yellow",
        nameTr: "Kinolin Sarısı",
        risk: "CAUTION",
        reason: "Quinoline Yellow is a synthetic dye banned in the USA, Australia, Japan, and Norway. Studies suggest it may cause hyperactivity and attention problems in children. In the EU, products containing it must carry warnings. It's often found in smoked fish, ice cream, and scotch eggs.",
        reasonTr:
            "Kinolin Sarısı, ABD, Avustralya, Japonya ve Norveç'te yasaklanmış sentetik bir boyadır. Çalışmalar, çocuklarda hiperaktivite ve dikkat sorunlarına neden olabileceğini göstermektedir. AB'de bunu içeren ürünler uyarı taşımalıdır. Genellikle füme balık, dondurma ve İskoç yumurtasında bulunur.",
        euStatus: "RESTRICTED",
        fdaStatus: "BANNED",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E110: {
        code: "E110",
        name: "Sunset Yellow (Yellow 6)",
        nameTr: "Gün Batımı Sarısı (Sarı 6)",
        risk: "CAUTION",
        reason: "Sunset Yellow is an orange-yellow dye commonly found in soft drinks, candies, and snacks. Multiple studies have linked it to hyperactivity in children. It may also cause allergic reactions including hives and nasal congestion. The EU requires mandatory warning labels on products containing this dye.",
        reasonTr:
            "Gün Batımı Sarısı, yaygın olarak meşrubatlarda, şekerlemelerde ve atıştırmalıklarda bulunan turuncu-sarı bir boyadır. Çok sayıda çalışma, çocuklarda hiperaktivite ile ilişkilendirmiştir. Ayrıca kurdeşen ve burun tıkanıklığı dahil alerjik reaksiyonlara neden olabilir. AB, bu boyayı içeren ürünlerde zorunlu uyarı etiketleri gerektirir.",
        euStatus: "RESTRICTED",
        fdaStatus: "GRAS",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E122: {
        code: "E122",
        name: "Carmoisine (Azorubine)",
        nameTr: "Karmoisin (Azorubin)",
        risk: "CAUTION",
        reason: "Carmoisine is a red synthetic dye banned in the USA, Japan, and several other countries. It's associated with allergic reactions, particularly in people sensitive to aspirin, and can trigger asthma attacks. Studies have also linked it to hyperactivity in children.",
        reasonTr: "Karmoisin, ABD, Japonya ve diğer birçok ülkede yasaklanmış kırmızı sentetik bir boyadır. Özellikle aspirine duyarlı kişilerde alerjik reaksiyonlarla ilişkilendirilir ve astım ataklarını tetikleyebilir. Çalışmalar ayrıca çocuklarda hiperaktivite ile ilişkilendirmiştir.",
        euStatus: "RESTRICTED",
        fdaStatus: "BANNED",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E124: {
        code: "E124",
        name: "Ponceau 4R (Red 7)",
        nameTr: "Ponso 4R (Kırmızı 7)",
        risk: "CAUTION",
        reason: "Ponceau 4R is a strawberry-red synthetic dye banned in the USA and Norway. It's one of the 'Southampton Six' dyes linked to hyperactivity in children. It can cause allergic reactions and is not recommended for children or people with aspirin sensitivity or asthma.",
        reasonTr:
            "Ponso 4R, ABD ve Norveç'te yasaklanmış çilek kırmızısı sentetik bir boyadır. Çocuklarda hiperaktivite ile ilişkilendirilen 'Southampton Altılısı' boyalardan biridir. Alerjik reaksiyonlara neden olabilir ve çocuklar veya aspirin hassasiyeti ya da astımı olan kişiler için önerilmez.",
        euStatus: "RESTRICTED",
        fdaStatus: "BANNED",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E129: {
        code: "E129",
        name: "Allura Red (Red 40)",
        nameTr: "Allura Kırmızısı (Kırmızı 40)",
        risk: "CAUTION",
        reason: "Allura Red is the most widely used red dye in the food industry. Studies have linked it to hyperactivity and behavioral problems in children. Recent research suggests it may increase intestinal inflammation and affect gut bacteria. The EU requires warning labels, while some countries have banned it entirely.",
        reasonTr:
            "Allura Kırmızısı, gıda endüstrisinde en yaygın kullanılan kırmızı boyadır. Çalışmalar, çocuklarda hiperaktivite ve davranış sorunlarıyla ilişkilendirmiştir. Son araştırmalar, bağırsak iltihabını artırabileceğini ve bağırsak bakterilerini etkileyebileceğini göstermektedir. AB uyarı etiketleri gerektirirken, bazı ülkeler tamamen yasaklamıştır.",
        euStatus: "RESTRICTED",
        fdaStatus: "GRAS",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E133: {
        code: "E133",
        name: "Brilliant Blue FCF",
        nameTr: "Parlak Mavi FCF",
        risk: "CAUTION",
        reason: "Brilliant Blue is a synthetic dye that can cause allergic reactions in sensitive individuals, including hives, asthma, and hay fever. Some studies suggest it may be able to cross the blood-brain barrier. It's commonly found in candies, beverages, and ice cream.",
        reasonTr: "Parlak Mavi, hassas bireylerde kurdeşen, astım ve saman nezlesi dahil alerjik reaksiyonlara neden olabilen sentetik bir boyadır. Bazı çalışmalar kan-beyin bariyerini geçebileceğini göstermektedir. Yaygın olarak şekerlemelerde, içeceklerde ve dondurmada bulunur.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E150C: {
        code: "E150C",
        name: "Ammonia Caramel",
        nameTr: "Amonyak Karameli",
        risk: "CAUTION",
        reason: "Ammonia Caramel is produced by heating sugar with ammonia compounds. This process creates 4-methylimidazole (4-MEI), a chemical classified as a possible carcinogen. It's commonly found in cola drinks, soy sauce, and dark beers. California requires cancer warning labels on products with high 4-MEI levels.",
        reasonTr:
            "Amonyak Karameli, şekerin amonyak bileşikleriyle ısıtılmasıyla üretilir. Bu işlem, olası kanserojen olarak sınıflandırılan 4-metilimidazol (4-MEI) oluşturur. Yaygın olarak kolalı içeceklerde, soya sosunda ve koyu biralarda bulunur. Kaliforniya, yüksek 4-MEI seviyeli ürünlerde kanser uyarı etiketleri gerektirir.",
        euStatus: "ALLOWED",
        fdaStatus: "WARNING",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E150D: {
        code: "E150D",
        name: "Sulphite Ammonia Caramel",
        nameTr: "Sülfit Amonyak Karameli",
        risk: "CAUTION",
        reason: "Sulphite Ammonia Caramel is the most commonly used caramel color, found in most cola drinks worldwide. Like E150c, it contains 4-MEI, a potential carcinogen. Studies have shown that regular consumption of products high in this additive may pose long-term health risks.",
        reasonTr:
            "Sülfit Amonyak Karameli, dünya genelinde çoğu kolalı içecekte bulunan en yaygın kullanılan karamel renklendiricidir. E150c gibi, potansiyel kanserojen olan 4-MEI içerir. Çalışmalar, bu katkı maddesinin yüksek olduğu ürünlerin düzenli tüketiminin uzun vadeli sağlık riskleri oluşturabileceğini göstermiştir.",
        euStatus: "ALLOWED",
        fdaStatus: "WARNING",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E211: {
        code: "E211",
        name: "Sodium Benzoate",
        nameTr: "Sodyum Benzoat",
        risk: "CAUTION",
        reason: "Sodium Benzoate is a preservative that can react with vitamin C (ascorbic acid) to form benzene, a known carcinogen. This reaction is accelerated by heat and light. It has also been linked to hyperactivity in children and can trigger allergies in sensitive individuals. Common in soft drinks and acidic foods.",
        reasonTr:
            "Sodyum Benzoat, bilinen bir kanserojen olan benzen oluşturmak için C vitamini (askorbik asit) ile reaksiyona girebilen bir koruyucudur. Bu reaksiyon ısı ve ışıkla hızlanır. Ayrıca çocuklarda hiperaktivite ile ilişkilendirilmiş ve hassas bireylerde alerjileri tetikleyebilir. Meşrubatlarda ve asitli gıdalarda yaygındır.",
        euStatus: "RESTRICTED",
        fdaStatus: "GRAS",
        category: "preservative",
        categoryTr: "Koruyucu",
    },
    E320: {
        code: "E320",
        name: "Butylated Hydroxyanisole (BHA)",
        nameTr: "Bütillenmiş Hidroksianisol (BHA)",
        risk: "CAUTION",
        reason: "BHA is an antioxidant preservative classified as 'reasonably anticipated to be a human carcinogen' by the US National Toxicology Program. It can cause allergic reactions and has been shown to affect hormones. It's commonly found in chips, cereals, and chewing gum. Several countries have restricted its use.",
        reasonTr:
            "BHA, ABD Ulusal Toksikoloji Programı tarafından 'makul olarak insan kanserojen olması beklenen' olarak sınıflandırılan antioksidan bir koruyucudur. Alerjik reaksiyonlara neden olabilir ve hormonları etkilediği gösterilmiştir. Yaygın olarak cipslerde, tahıllarda ve sakızda bulunur. Birçok ülke kullanımını kısıtlamıştır.",
        euStatus: "RESTRICTED",
        fdaStatus: "GRAS",
        category: "antioxidant",
        categoryTr: "Antioksidan",
    },
    E321: {
        code: "E321",
        name: "Butylated Hydroxytoluene (BHT)",
        nameTr: "Bütillenmiş Hidroksitoluen (BHT)",
        risk: "CAUTION",
        reason: "BHT is closely related to BHA and shares similar concerns. It's suspected of being an endocrine disruptor, potentially affecting thyroid hormone levels. Some studies have linked it to tumor promotion in animals. It can cause allergic skin reactions and is banned in food in Japan and some European countries.",
        reasonTr:
            "BHT, BHA ile yakından ilişkilidir ve benzer endişeleri paylaşır. Potansiyel olarak tiroid hormon seviyelerini etkileyen endokrin bozucu olduğundan şüphelenilmektedir. Bazı çalışmalar, hayvanlarda tümör gelişimiyle ilişkilendirmiştir. Alerjik cilt reaksiyonlarına neden olabilir ve Japonya ile bazı Avrupa ülkelerinde gıdalarda yasaklanmıştır.",
        euStatus: "RESTRICTED",
        fdaStatus: "GRAS",
        category: "antioxidant",
        categoryTr: "Antioksidan",
    },
    E407: {
        code: "E407",
        name: "Carrageenan",
        nameTr: "Karragenan",
        risk: "CAUTION",
        reason: "Carrageenan is derived from seaweed and used as a thickener. While naturally sourced, degraded carrageenan has been linked to intestinal inflammation, ulcers, and potentially colon cancer. Some studies suggest even food-grade carrageenan may cause digestive issues in sensitive individuals. It's common in dairy alternatives and processed foods.",
        reasonTr:
            "Karragenan, deniz yosunundan elde edilir ve kıvam arttırıcı olarak kullanılır. Doğal kaynaklı olmasına rağmen, bozunmuş karragenan bağırsak iltihabı, ülser ve potansiyel olarak kolon kanseri ile ilişkilendirilmiştir. Bazı çalışmalar, gıda kalitesindeki karragenanın bile hassas bireylerde sindirim sorunlarına neden olabileceğini göstermektedir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "thickener",
        categoryTr: "Kıvam Arttırıcı",
    },
    E450: {
        code: "E450",
        name: "Diphosphates",
        nameTr: "Difosfatlar",
        risk: "CAUTION",
        reason: "Diphosphates are commonly used in processed meats, baked goods, and cheese products. Excessive phosphate intake can disrupt calcium balance, potentially weakening bones. High phosphate consumption has been linked to increased cardiovascular risk and kidney strain. People with kidney problems should limit intake.",
        reasonTr:
            "Difosfatlar, yaygın olarak işlenmiş etlerde, unlu mamullerde ve peynir ürünlerinde kullanılır. Aşırı fosfat alımı kalsiyum dengesini bozabilir ve potansiyel olarak kemikleri zayıflatabilir. Yüksek fosfat tüketimi, artan kardiyovasküler risk ve böbrek yükü ile ilişkilendirilmiştir. Böbrek sorunu olan kişiler alımı sınırlamalıdır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "acidity_regulator",
        categoryTr: "Asitlik Düzenleyici",
    },
    E451: {
        code: "E451",
        name: "Triphosphates",
        nameTr: "Trifosfatlar",
        risk: "CAUTION",
        reason: "Triphosphates are used to retain moisture in processed meats and seafood. Like other phosphates, they can interfere with calcium and magnesium absorption, potentially affecting bone health. High consumption may contribute to mineral imbalances and has been associated with cardiovascular concerns in people with kidney disease.",
        reasonTr:
            "Trifosfatlar, işlenmiş etlerde ve deniz ürünlerinde nemi tutmak için kullanılır. Diğer fosfatlar gibi, kalsiyum ve magnezyum emilimini engelleyebilir ve potansiyel olarak kemik sağlığını etkileyebilir. Yüksek tüketim mineral dengesizliklerine katkıda bulunabilir ve böbrek hastalığı olan kişilerde kardiyovasküler endişelerle ilişkilendirilmiştir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "acidity_regulator",
        categoryTr: "Asitlik Düzenleyici",
    },
    E452: {
        code: "E452",
        name: "Polyphosphates",
        nameTr: "Polifosfatlar",
        risk: "CAUTION",
        reason: "Polyphosphates are widely used in processed foods to improve texture and extend shelf life. They can bind to calcium in the digestive tract, reducing absorption and potentially contributing to calcium deficiency over time. Research suggests excessive phosphate intake may accelerate aging of blood vessels.",
        reasonTr:
            "Polifosfatlar, dokuyu iyileştirmek ve raf ömrünü uzatmak için işlenmiş gıdalarda yaygın olarak kullanılır. Sindirim sisteminde kalsiyuma bağlanabilir, emilimi azaltabilir ve zamanla potansiyel olarak kalsiyum eksikliğine katkıda bulunabilir. Araştırmalar, aşırı fosfat alımının kan damarlarının yaşlanmasını hızlandırabileceğini göstermektedir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "acidity_regulator",
        categoryTr: "Asitlik Düzenleyici",
    },
    E621: {
        code: "E621",
        name: "Monosodium Glutamate (MSG)",
        nameTr: "Monosodyum Glutamat (MSG)",
        risk: "CAUTION",
        reason: "MSG is a flavor enhancer that can cause 'Chinese Restaurant Syndrome' in sensitive individuals, with symptoms including headaches, flushing, sweating, and chest pain. While generally recognized as safe, some people report adverse reactions. It may also contribute to overeating by making food more palatable.",
        reasonTr:
            "MSG, hassas bireylerde baş ağrısı, yüz kızarması, terleme ve göğüs ağrısı gibi semptomlarla 'Çin Restoranı Sendromu'na neden olabilen bir lezzet arttırıcıdır. Genel olarak güvenli kabul edilse de, bazı kişiler olumsuz reaksiyonlar bildirmektedir. Ayrıca yiyecekleri daha lezzetli hale getirerek aşırı yemeye katkıda bulunabilir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "flavor_enhancer",
        categoryTr: "Lezzet Arttırıcı",
    },
    E951: {
        code: "E951",
        name: "Aspartame",
        nameTr: "Aspartam",
        risk: "CAUTION",
        reason: "Aspartame is an artificial sweetener that is dangerous for people with phenylketonuria (PKU), a genetic disorder. Products containing it must carry PKU warnings. Some studies have raised concerns about potential links to headaches, mood changes, and cancer, though regulatory bodies consider it safe at approved levels.",
        reasonTr:
            "Aspartam, genetik bir bozukluk olan fenilketonüri (PKU) hastası kişiler için tehlikeli olan yapay bir tatlandırıcıdır. İçeren ürünler PKU uyarıları taşımalıdır. Bazı çalışmalar baş ağrısı, ruh hali değişiklikleri ve kanserle potansiyel bağlantılar konusunda endişelere yol açmıştır, ancak düzenleyici kurumlar onaylı seviyelerde güvenli kabul etmektedir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "sweetener",
        categoryTr: "Tatlandırıcı",
    },
    E950: {
        code: "E950",
        name: "Acesulfame Potassium (Ace-K)",
        nameTr: "Asesülfam Potasyum (Ace-K)",
        risk: "CAUTION",
        reason: "Acesulfame K is an artificial sweetener often combined with other sweeteners. Some animal studies have raised concerns about potential carcinogenic effects, though these findings are debated. The long-term effects of regular consumption are not fully understood. It contains methylene chloride, a potential carcinogen.",
        reasonTr:
            "Asesülfam K, genellikle diğer tatlandırıcılarla birleştirilen yapay bir tatlandırıcıdır. Bazı hayvan çalışmaları potansiyel kanserojen etkiler konusunda endişelere yol açmıştır, ancak bu bulgular tartışmalıdır. Düzenli tüketimin uzun vadeli etkileri tam olarak anlaşılamamıştır. Potansiyel kanserojen olan metilen klorür içerir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "sweetener",
        categoryTr: "Tatlandırıcı",
    },
    E955: {
        code: "E955",
        name: "Sucralose",
        nameTr: "Sukraloz",
        risk: "CAUTION",
        reason: "Sucralose is a zero-calorie sweetener that recent studies suggest may negatively affect gut bacteria and glucose metabolism. When heated, it can break down into potentially harmful chlorinated compounds. Some research indicates it may not be as metabolically inert as once believed.",
        reasonTr:
            "Sukraloz, son çalışmaların bağırsak bakterilerini ve glikoz metabolizmasını olumsuz etkileyebileceğini gösterdiği sıfır kalorili bir tatlandırıcıdır. Isıtıldığında potansiyel olarak zararlı klorlu bileşiklere parçalanabilir. Bazı araştırmalar, bir zamanlar inanıldığı kadar metabolik olarak etkisiz olmayabileceğini göstermektedir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "sweetener",
        categoryTr: "Tatlandırıcı",
    },

    // SAFE - GÜVENLİ

    E100: {
        code: "E100",
        name: "Curcumin",
        nameTr: "Kurkumin",
        risk: "SAFE",
        reason: "Curcumin is the natural yellow pigment found in turmeric. It has powerful anti-inflammatory and antioxidant properties and has been used in traditional medicine for thousands of years. Studies suggest it may help protect against heart disease, Alzheimer's, and cancer. It's one of the safest food colorants available.",
        reasonTr:
            "Kurkumin, zerdeçalda bulunan doğal sarı pigmenttir. Güçlü anti-inflamatuar ve antioksidan özelliklere sahiptir ve geleneksel tıpta binlerce yıldır kullanılmaktadır. Çalışmalar kalp hastalığı, Alzheimer ve kansere karşı korumaya yardımcı olabileceğini göstermektedir. Mevcut en güvenli gıda renklendiricilerinden biridir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E101: {
        code: "E101",
        name: "Riboflavin (Vitamin B2)",
        nameTr: "Riboflavin (B2 Vitamini)",
        risk: "SAFE",
        reason: "Riboflavin is vitamin B2, an essential nutrient that gives foods a yellow color. It plays a crucial role in energy production and cellular function. As a vitamin, it's not only safe but beneficial to health. Excess amounts are simply excreted in urine, giving it a bright yellow color.",
        reasonTr:
            "Riboflavin, gıdalara sarı renk veren temel bir besin olan B2 vitaminidir. Enerji üretiminde ve hücresel fonksiyonda önemli bir rol oynar. Bir vitamin olarak sadece güvenli değil, aynı zamanda sağlığa faydalıdır. Fazla miktarlar basitçe idrarla atılır ve parlak sarı bir renk verir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E160A: {
        code: "E160A",
        name: "Beta-Carotene",
        nameTr: "Beta-Karoten",
        risk: "SAFE",
        reason: "Beta-Carotene is the natural orange pigment found in carrots, sweet potatoes, and other vegetables. The body converts it to vitamin A as needed, making it a safe source of this essential nutrient. It's a powerful antioxidant that may help protect against certain cancers and eye diseases.",
        reasonTr:
            "Beta-Karoten, havuç, tatlı patates ve diğer sebzelerde bulunan doğal turuncu pigmenttir. Vücut gerektiğinde A vitaminine dönüştürür, bu da onu bu temel besinin güvenli bir kaynağı yapar. Belirli kanserlere ve göz hastalıklarına karşı korumaya yardımcı olabilecek güçlü bir antioksidandır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E160C: {
        code: "E160C",
        name: "Paprika Extract",
        nameTr: "Kırmızı Biber Özütü",
        risk: "SAFE",
        reason: "Paprika Extract is a natural red-orange colorant derived from sweet red peppers. It contains beneficial carotenoids and has antioxidant properties. It's commonly used to add color to cheeses, sauces, and snacks. As a natural plant extract, it's considered very safe for consumption.",
        reasonTr:
            "Kırmızı Biber Özütü, tatlı kırmızı biberlerden elde edilen doğal kırmızı-turuncu bir renklendiricidir. Faydalı karotenoidler içerir ve antioksidan özelliklere sahiptir. Yaygın olarak peynirlere, soslara ve atıştırmalıklara renk katmak için kullanılır. Doğal bir bitki özütü olarak tüketim için çok güvenli kabul edilir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E162: {
        code: "E162",
        name: "Beetroot Red (Betanin)",
        nameTr: "Pancar Kırmızısı (Betanin)",
        risk: "SAFE",
        reason: "Beetroot Red is a natural pigment extracted from beets. It provides a vibrant red-purple color and contains betalains, which have antioxidant and anti-inflammatory properties. It's completely safe and may even offer health benefits. Common in ice cream, yogurt, and candies.",
        reasonTr: "Pancar Kırmızısı, pancardan elde edilen doğal bir pigmenttir. Canlı kırmızı-mor renk sağlar ve antioksidan ve anti-inflamatuar özelliklere sahip betalainler içerir. Tamamen güvenlidir ve hatta sağlık yararları bile sunabilir. Dondurma, yoğurt ve şekerlemelerde yaygındır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E163: {
        code: "E163",
        name: "Anthocyanins",
        nameTr: "Antosiyaninler",
        risk: "SAFE",
        reason: "Anthocyanins are natural pigments that give berries, grapes, and red cabbage their vibrant colors. They are powerful antioxidants with numerous health benefits, including supporting heart health and cognitive function. They may help reduce inflammation and protect against certain diseases.",
        reasonTr:
            "Antosiyaninler, meyvelerine, üzümlere ve kırmızı lahanaya canlı renklerini veren doğal pigmentlerdir. Kalp sağlığını ve bilişsel işlevi desteklemek dahil çok sayıda sağlık yararı olan güçlü antioksidanlardır. İltihabı azaltmaya ve belirli hastalıklara karşı korumaya yardımcı olabilirler.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E170: {
        code: "E170",
        name: "Calcium Carbonate",
        nameTr: "Kalsiyum Karbonat",
        risk: "SAFE",
        reason: "Calcium Carbonate is simply chalk or limestone - a natural mineral. It's used as a white colorant and anti-caking agent. It also provides calcium, an essential mineral for bone health. It's so safe that it's commonly used as a dietary calcium supplement and antacid.",
        reasonTr:
            "Kalsiyum Karbonat, basitçe tebeşir veya kireçtaşıdır - doğal bir mineral. Beyaz renklendirici ve topaklanma önleyici olarak kullanılır. Ayrıca kemik sağlığı için temel bir mineral olan kalsiyum sağlar. O kadar güvenlidir ki, yaygın olarak diyet kalsiyum takviyesi ve antiasit olarak kullanılır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "colorant",
        categoryTr: "Renklendirici",
    },
    E270: {
        code: "E270",
        name: "Lactic Acid",
        nameTr: "Laktik Asit",
        risk: "SAFE",
        reason: "Lactic Acid is naturally produced during fermentation and is found in yogurt, sauerkraut, and sourdough bread. It's also produced by our muscles during exercise. As a food additive, it acts as a preservative and flavor enhancer. It's completely natural and safe for consumption.",
        reasonTr:
            "Laktik Asit, fermantasyon sırasında doğal olarak üretilir ve yoğurt, lahana turşusu ve ekşi maya ekmeğinde bulunur. Ayrıca egzersiz sırasında kaslarımız tarafından da üretilir. Gıda katkı maddesi olarak koruyucu ve lezzet arttırıcı görevi görür. Tamamen doğaldır ve tüketim için güvenlidir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "preservative",
        categoryTr: "Koruyucu",
    },
    E290: {
        code: "E290",
        name: "Carbon Dioxide",
        nameTr: "Karbondioksit",
        risk: "SAFE",
        reason: "Carbon Dioxide is the gas that makes beverages fizzy. It's a natural component of the air we exhale and is completely harmless in food applications. It's used to carbonate drinks, preserve food by creating an oxygen-free environment, and as a propellant in whipped cream cans.",
        reasonTr: "Karbondioksit, içecekleri gazlı yapan gazdır. Soluduğumuz havanın doğal bir bileşenidir ve gıda uygulamalarında tamamen zararsızdır. İçecekleri gazlandırmak, oksijensiz ortam oluşturarak gıdaları korumak ve krem şanti kutularında itici gaz olarak kullanılır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "other",
        categoryTr: "Diğer",
    },
    E296: {
        code: "E296",
        name: "Malic Acid",
        nameTr: "Malik Asit",
        risk: "SAFE",
        reason: "Malic Acid is the natural acid that gives apples their tart taste. It's found in many fruits and is produced naturally in our bodies during metabolism. As a food additive, it provides a sour flavor and helps preserve freshness. It's completely safe and natural.",
        reasonTr: "Malik Asit, elmalara ekşi tadını veren doğal asittir. Birçok meyvede bulunur ve metabolizma sırasında vücudumuzda doğal olarak üretilir. Gıda katkı maddesi olarak ekşi lezzet sağlar ve tazeliği korumaya yardımcı olur. Tamamen güvenli ve doğaldır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "acidity_regulator",
        categoryTr: "Asitlik Düzenleyici",
    },
    E300: {
        code: "E300",
        name: "Ascorbic Acid (Vitamin C)",
        nameTr: "Askorbik Asit (C Vitamini)",
        risk: "SAFE",
        reason: "Ascorbic Acid is simply vitamin C, an essential nutrient that our bodies cannot produce. It's a powerful antioxidant that supports immune function, skin health, and iron absorption. As a food additive, it prevents browning and acts as a preservative. It's not only safe but beneficial.",
        reasonTr:
            "Askorbik Asit, vücudumuzun üretemediği temel bir besin olan C vitaminidir. Bağışıklık fonksiyonunu, cilt sağlığını ve demir emilimini destekleyen güçlü bir antioksidandır. Gıda katkı maddesi olarak kararmaları önler ve koruyucu görevi görür. Sadece güvenli değil, aynı zamanda faydalıdır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "antioxidant",
        categoryTr: "Antioksidan",
    },
    E301: {
        code: "E301",
        name: "Sodium Ascorbate",
        nameTr: "Sodyum Askorbat",
        risk: "SAFE",
        reason: "Sodium Ascorbate is a mineral salt form of vitamin C. It's less acidic than ascorbic acid, making it gentler on the stomach. It provides the same antioxidant benefits as vitamin C and is commonly used in cured meats as a healthier alternative to nitrites.",
        reasonTr:
            "Sodyum Askorbat, C vitamininin mineral tuz formudur. Askorbik asitten daha az asidiktir, bu da mideye karşı daha yumuşak olmasını sağlar. C vitaminiyle aynı antioksidan faydaları sağlar ve kürlenmış etlerde nitritlere daha sağlıklı bir alternatif olarak yaygın şekilde kullanılır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "antioxidant",
        categoryTr: "Antioksidan",
    },
    E306: {
        code: "E306",
        name: "Tocopherols (Vitamin E)",
        nameTr: "Tokoferoller (E Vitamini)",
        risk: "SAFE",
        reason: "Tocopherols are the natural forms of vitamin E, an essential fat-soluble antioxidant. They protect cell membranes from damage and support immune function. As a food additive, they prevent fats from going rancid. Found naturally in nuts, seeds, and vegetable oils.",
        reasonTr: "Tokoferoller, temel yağda çözünür bir antioksidan olan E vitamininin doğal formlarıdır. Hücre zarlarını hasardan korur ve bağışıklık fonksiyonunu destekler. Gıda katkı maddesi olarak yağların acımasını önler. Doğal olarak kuruyemişlerde, tohumlarda ve bitkisel yağlarda bulunur.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "antioxidant",
        categoryTr: "Antioksidan",
    },
    E322: {
        code: "E322",
        name: "Lecithin",
        nameTr: "Lesitin",
        risk: "SAFE",
        reason: "Lecithin is a natural emulsifier found in egg yolks and soybeans. It helps oil and water mix together smoothly. It's an important component of cell membranes and supports brain function. Lecithin supplements are even taken for their potential cognitive and liver health benefits.",
        reasonTr:
            "Lesitin, yumurta sarısı ve soya fasulyesinde bulunan doğal bir emülgatördür. Yağ ve suyun düzgün bir şekilde karışmasına yardımcı olur. Hücre zarlarının önemli bir bileşenidir ve beyin fonksiyonunu destekler. Lesitin takviyeleri potansiyel bilişsel ve karaciğer sağlığı faydaları için bile alınmaktadır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "emulsifier",
        categoryTr: "Emülgatör",
    },
    E330: {
        code: "E330",
        name: "Citric Acid",
        nameTr: "Sitrik Asit",
        risk: "SAFE",
        reason: "Citric Acid is naturally found in citrus fruits and gives them their sour taste. It's also produced naturally in our bodies as part of energy metabolism. As a food additive, it provides tartness, acts as a preservative, and enhances flavors. It's one of the most common and safest food additives.",
        reasonTr:
            "Sitrik Asit, doğal olarak narenciye meyvelerinde bulunur ve onlara ekşi tadını verir. Ayrıca enerji metabolizmasının bir parçası olarak vücudumuzda doğal olarak üretilir. Gıda katkı maddesi olarak ekşilik sağlar, koruyucu görevi görür ve lezzetleri artırır. En yaygın ve en güvenli gıda katkı maddelerinden biridir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "acidity_regulator",
        categoryTr: "Asitlik Düzenleyici",
    },
    E331: {
        code: "E331",
        name: "Sodium Citrate",
        nameTr: "Sodyum Sitrat",
        risk: "SAFE",
        reason: "Sodium Citrate is the sodium salt of citric acid. It's used as an acidity regulator and emulsifier. It helps create the smooth texture in processed cheese and ice cream. It's also used medically to treat kidney stones and urinary tract infections. Completely safe for consumption.",
        reasonTr:
            "Sodyum Sitrat, sitrik asidin sodyum tuzudur. Asitlik düzenleyici ve emülgatör olarak kullanılır. İşlenmiş peynir ve dondurmada pürüzsüz doku oluşturmaya yardımcı olur. Ayrıca tıbbi olarak böbrek taşları ve idrar yolu enfeksiyonlarını tedavi etmek için kullanılır. Tüketim için tamamen güvenlidir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "acidity_regulator",
        categoryTr: "Asitlik Düzenleyici",
    },
    E332: {
        code: "E332",
        name: "Potassium Citrate",
        nameTr: "Potasyum Sitrat",
        risk: "SAFE",
        reason: "Potassium Citrate provides both citrate (for acidity regulation) and potassium (an essential mineral). It's used in beverages and food products and is also a common dietary supplement. It can help prevent kidney stones and provides important electrolytes.",
        reasonTr: "Potasyum Sitrat, hem sitrat (asitlik düzenlemesi için) hem de potasyum (temel bir mineral) sağlar. İçeceklerde ve gıda ürünlerinde kullanılır ve ayrıca yaygın bir diyet takviyesidir. Böbrek taşlarını önlemeye yardımcı olabilir ve önemli elektrolitler sağlar.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "acidity_regulator",
        categoryTr: "Asitlik Düzenleyici",
    },
    E333: {
        code: "E333",
        name: "Calcium Citrate",
        nameTr: "Kalsiyum Sitrat",
        risk: "SAFE",
        reason: "Calcium Citrate is an excellent source of bioavailable calcium, better absorbed than calcium carbonate. It's used to fortify foods and beverages with calcium. It also acts as an acidity regulator. It's commonly used as a calcium supplement for bone health.",
        reasonTr:
            "Kalsiyum Sitrat, kalsiyum karbonattan daha iyi emilen, biyoyararlanılabilir kalsiyumun mükemmel bir kaynağıdır. Gıdaları ve içecekleri kalsiyumla zenginleştirmek için kullanılır. Ayrıca asitlik düzenleyici görevi görür. Kemik sağlığı için yaygın olarak kalsiyum takviyesi olarak kullanılır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "acidity_regulator",
        categoryTr: "Asitlik Düzenleyici",
    },
    E334: {
        code: "E334",
        name: "Tartaric Acid",
        nameTr: "Tartarik Asit",
        risk: "SAFE",
        reason: "Tartaric Acid occurs naturally in grapes and is a byproduct of winemaking. It provides a distinctive tart taste and is essential in baking powder. It has antioxidant properties and is completely safe. It's one of the oldest known food acids, used for centuries.",
        reasonTr: "Tartarik Asit, doğal olarak üzümlerde bulunur ve şarap yapımının bir yan ürünüdür. Belirgin ekşi tat sağlar ve kabartma tozunda gereklidir. Antioksidan özelliklere sahiptir ve tamamen güvenlidir. Yüzyıllardır kullanılan en eski bilinen gıda asitlerinden biridir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "acidity_regulator",
        categoryTr: "Asitlik Düzenleyici",
    },
    E335: {
        code: "E335",
        name: "Sodium Tartrate",
        nameTr: "Sodyum Tartrat",
        risk: "SAFE",
        reason: "Sodium Tartrate is the sodium salt of tartaric acid. It's used as an emulsifier and stabilizer in food products. It helps maintain texture and consistency. Like tartaric acid, it's derived from natural grape processing and is completely safe.",
        reasonTr: "Sodyum Tartrat, tartarik asidin sodyum tuzudur. Gıda ürünlerinde emülgatör ve stabilizatör olarak kullanılır. Doku ve kıvamı korumaya yardımcı olur. Tartarik asit gibi, doğal üzüm işlemesinden elde edilir ve tamamen güvenlidir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "acidity_regulator",
        categoryTr: "Asitlik Düzenleyici",
    },
    E336: {
        code: "E336",
        name: "Potassium Tartrate (Cream of Tartar)",
        nameTr: "Potasyum Tartrat (Krem Tartar)",
        risk: "SAFE",
        reason: "Potassium Tartrate, known as cream of tartar, is a natural byproduct of winemaking. It's essential in baking for stabilizing egg whites and creating fluffy textures. It's been used in cooking for centuries and provides a small amount of potassium. Completely natural and safe.",
        reasonTr:
            "Krem tartar olarak bilinen Potasyum Tartrat, şarap yapımının doğal bir yan ürünüdür. Yumurta aklarını stabilize etmek ve kabarık dokular oluşturmak için fırıncılıkta gereklidir. Yüzyıllardır yemek pişirmede kullanılmaktadır ve az miktarda potasyum sağlar. Tamamen doğal ve güvenlidir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "acidity_regulator",
        categoryTr: "Asitlik Düzenleyici",
    },
    E392: {
        code: "E392",
        name: "Rosemary Extract",
        nameTr: "Biberiye Özütü",
        risk: "SAFE",
        reason: "Rosemary Extract is a natural antioxidant derived from the rosemary herb. It's highly effective at preventing fats from going rancid and extending shelf life. It contains beneficial compounds like rosmarinic acid and carnosic acid. A natural alternative to synthetic antioxidants.",
        reasonTr: "Biberiye Özütü, biberiye bitkisinden elde edilen doğal bir antioksidandır. Yağların acımasını önlemede ve raf ömrünü uzatmada oldukça etkilidir. Rosmarinik asit ve karnosik asit gibi faydalı bileşikler içerir. Sentetik antioksidanlara doğal bir alternatiftir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "antioxidant",
        categoryTr: "Antioksidan",
    },
    E400: {
        code: "E400",
        name: "Alginic Acid",
        nameTr: "Aljinik Asit",
        risk: "SAFE",
        reason: "Alginic Acid is extracted from brown seaweed. It's a natural thickener and gelling agent used in ice cream, desserts, and sauces. It's also used medically in heartburn remedies where it forms a protective barrier. High in fiber and completely safe.",
        reasonTr: "Aljinik Asit, kahverengi deniz yosunundan elde edilir. Dondurma, tatlılar ve soslarda kullanılan doğal bir kıvam arttırıcı ve jelleştirici ajandır. Ayrıca koruyucu bariyer oluşturduğu mide yanması ilaçlarında tıbbi olarak kullanılır. Lif açısından zengin ve tamamen güvenlidir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "thickener",
        categoryTr: "Kıvam Arttırıcı",
    },
    E401: {
        code: "E401",
        name: "Sodium Alginate",
        nameTr: "Sodyum Aljinat",
        risk: "SAFE",
        reason: "Sodium Alginate is derived from seaweed and is famous for its use in molecular gastronomy to create 'caviar pearls' and other innovative textures. It's also used in traditional food production as a thickener. It's a source of dietary fiber and completely safe.",
        reasonTr: "Sodyum Aljinat, deniz yosunundan elde edilir ve moleküler gastronomide 'havyar incileri' ve diğer yenilikçi dokular oluşturmak için kullanımıyla ünlüdür. Ayrıca geleneksel gıda üretiminde kıvam arttırıcı olarak kullanılır. Diyet lifi kaynağıdır ve tamamen güvenlidir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "thickener",
        categoryTr: "Kıvam Arttırıcı",
    },
    E406: {
        code: "E406",
        name: "Agar (Agar-Agar)",
        nameTr: "Agar (Agar-Agar)",
        risk: "SAFE",
        reason: "Agar is a natural gelling agent derived from red seaweed. It's been used in Asian cuisine for centuries and is the perfect vegan alternative to gelatin. It sets at room temperature and provides dietary fiber. Also used in scientific laboratories for growing bacteria cultures.",
        reasonTr:
            "Agar, kırmızı deniz yosunundan elde edilen doğal bir jelleştirici ajandır. Asya mutfağında yüzyıllardır kullanılmaktadır ve jelatine mükemmel vegan alternatiftir. Oda sıcaklığında donar ve diyet lifi sağlar. Ayrıca bilimsel laboratuvarlarda bakteri kültürleri yetiştirmek için kullanılır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "thickener",
        categoryTr: "Kıvam Arttırıcı",
    },
    E410: {
        code: "E410",
        name: "Locust Bean Gum (Carob Gum)",
        nameTr: "Keçiboynuzu Gamı (Harnup Gamı)",
        risk: "SAFE",
        reason: "Locust Bean Gum is extracted from carob tree seeds. It's a natural thickener that creates smooth, creamy textures in ice cream and dairy products. It's high in fiber and may help regulate blood sugar. Used for thousands of years in Mediterranean cuisine.",
        reasonTr: "Keçiboynuzu Gamı, keçiboynuzu ağacı tohumlarından elde edilir. Dondurma ve süt ürünlerinde pürüzsüz, kremsi dokular oluşturan doğal bir kıvam arttırıcıdır. Lif açısından zengindir ve kan şekerini düzenlemeye yardımcı olabilir. Akdeniz mutfağında binlerce yıldır kullanılmaktadır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "thickener",
        categoryTr: "Kıvam Arttırıcı",
    },
    E412: {
        code: "E412",
        name: "Guar Gum",
        nameTr: "Guar Gamı",
        risk: "SAFE",
        reason: "Guar Gum is derived from guar beans and is one of the most effective natural thickeners. It can absorb many times its weight in water. It's a source of soluble fiber that may help lower cholesterol and blood sugar levels. Widely used in gluten-free baking.",
        reasonTr: "Guar Gamı, guar fasulyesinden elde edilir ve en etkili doğal kıvam arttırıcılardan biridir. Ağırlığının birçok katı suyu emebilir. Kolesterol ve kan şekeri seviyelerini düşürmeye yardımcı olabilecek çözünür lif kaynağıdır. Glutensiz fırıncılıkta yaygın olarak kullanılır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "thickener",
        categoryTr: "Kıvam Arttırıcı",
    },
    E414: {
        code: "E414",
        name: "Acacia Gum (Gum Arabic)",
        nameTr: "Akasya Gamı (Arap Gamı)",
        risk: "SAFE",
        reason: "Acacia Gum is harvested from acacia trees and has been used for thousands of years. It's a natural emulsifier and stabilizer used in soft drinks, candies, and many other products. It's a prebiotic fiber that supports beneficial gut bacteria. Completely safe and natural.",
        reasonTr:
            "Akasya Gamı, akasya ağaçlarından hasat edilir ve binlerce yıldır kullanılmaktadır. Meşrubatlarda, şekerlemelerde ve diğer birçok üründe kullanılan doğal bir emülgatör ve stabilizatördür. Faydalı bağırsak bakterilerini destekleyen prebiyotik bir liftir. Tamamen güvenli ve doğaldır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "thickener",
        categoryTr: "Kıvam Arttırıcı",
    },
    E415: {
        code: "E415",
        name: "Xanthan Gum",
        nameTr: "Ksantan Gamı",
        risk: "SAFE",
        reason: "Xanthan Gum is produced through fermentation of sugars. It's an incredibly effective thickener used in everything from salad dressings to gluten-free bread. It provides structure to baked goods without gluten. It's well-studied and considered very safe at typical consumption levels.",
        reasonTr: "Ksantan Gamı, şekerlerin fermantasyonu yoluyla üretilir. Salata soslarından glutensiz ekmeğe kadar her şeyde kullanılan inanılmaz etkili bir kıvam arttırıcıdır. Glutensiz unlu mamullere yapı sağlar. İyi araştırılmıştır ve tipik tüketim seviyelerinde çok güvenli kabul edilir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "thickener",
        categoryTr: "Kıvam Arttırıcı",
    },
    E440: {
        code: "E440",
        name: "Pectin",
        nameTr: "Pektin",
        risk: "SAFE",
        reason: "Pectin is a natural fiber found in fruits, especially apples and citrus peels. It's what makes jams and jellies set. It's a soluble fiber that may help lower cholesterol and regulate blood sugar. It's completely natural and provides health benefits beyond its functional use.",
        reasonTr:
            "Pektin, meyvelerde, özellikle elma ve narenciye kabuklarında bulunan doğal bir liftir. Reçellerin ve jölelerin katılaşmasını sağlayan maddedir. Kolesterolü düşürmeye ve kan şekerini düzenlemeye yardımcı olabilecek çözünür bir liftir. Tamamen doğaldır ve fonksiyonel kullanımının ötesinde sağlık yararları sağlar.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "thickener",
        categoryTr: "Kıvam Arttırıcı",
    },
    E460: {
        code: "E460",
        name: "Cellulose",
        nameTr: "Selüloz",
        risk: "SAFE",
        reason: "Cellulose is the main structural component of plant cell walls. It's indigestible fiber that aids digestion and helps you feel full. As a food additive, it prevents caking and adds texture. It's found naturally in all vegetables and fruits. Completely safe and beneficial.",
        reasonTr: "Selüloz, bitki hücre duvarlarının ana yapısal bileşenidir. Sindirimi kolaylaştıran ve tokluk hissi veren sindirilemez liftir. Gıda katkı maddesi olarak topaklanmayı önler ve doku katar. Doğal olarak tüm sebze ve meyvelerde bulunur. Tamamen güvenli ve faydalıdır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "thickener",
        categoryTr: "Kıvam Arttırıcı",
    },
    E500: {
        code: "E500",
        name: "Sodium Bicarbonate (Baking Soda)",
        nameTr: "Sodyum Bikarbonat (Karbonat)",
        risk: "SAFE",
        reason: "Sodium Bicarbonate, or baking soda, is a leavening agent that's been used in cooking for centuries. It reacts with acids to produce carbon dioxide, making baked goods rise. It's also used as an antacid and cleaning agent. One of the safest and most versatile additives.",
        reasonTr:
            "Karbonat veya kabartma tozu, yüzyıllardır yemek pişirmede kullanılan bir kabartma ajanıdır. Asitlerle reaksiyona girerek karbondioksit üretir ve unlu mamullerin kabarmasını sağlar. Ayrıca antiasit ve temizlik maddesi olarak kullanılır. En güvenli ve çok yönlü katkı maddelerinden biridir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "raising_agent",
        categoryTr: "Kabartıcı",
    },
    E501: {
        code: "E501",
        name: "Potassium Carbonate",
        nameTr: "Potasyum Karbonat",
        risk: "SAFE",
        reason: "Potassium Carbonate is a traditional leavening agent used especially in Asian cooking for noodles and mooncakes. It helps create unique textures in baked goods. It provides potassium, an essential mineral. It's been used safely in food for centuries.",
        reasonTr: "Potasyum Karbonat, özellikle Asya mutfağında erişte ve ay keki için kullanılan geleneksel bir kabartma ajanıdır. Unlu mamullerde benzersiz dokular oluşturmaya yardımcı olur. Temel bir mineral olan potasyum sağlar. Yüzyıllardır gıdalarda güvenle kullanılmaktadır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "raising_agent",
        categoryTr: "Kabartıcı",
    },
    E503: {
        code: "E503",
        name: "Ammonium Carbonate",
        nameTr: "Amonyum Karbonat",
        risk: "SAFE",
        reason: "Ammonium Carbonate is a traditional leavening agent also known as 'baker's ammonia.' It's been used since the 13th century and produces very crisp textures in cookies and crackers. The ammonia completely evaporates during baking, leaving no residue.",
        reasonTr: "Amonyum Karbonat, 'fırıncı amonyağı' olarak da bilinen geleneksel bir kabartma ajanıdır. 13. yüzyıldan beri kullanılmaktadır ve kurabiye ve krakerlerde çok kıtır dokular üretir. Amonyak pişirme sırasında tamamen buharlaşır ve kalıntı bırakmaz.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "raising_agent",
        categoryTr: "Kabartıcı",
    },
    E509: {
        code: "E509",
        name: "Calcium Chloride",
        nameTr: "Kalsiyum Klorür",
        risk: "SAFE",
        reason: "Calcium Chloride is used to maintain firmness in canned vegetables and fruits. It's also essential in cheese making and helps tofu set properly. It provides calcium, an important mineral. It's a natural compound found in seawater and mineral deposits.",
        reasonTr: "Kalsiyum Klorür, konserve sebze ve meyvelerde sertliği korumak için kullanılır. Ayrıca peynir yapımında gereklidir ve tofunun düzgün katılaşmasına yardımcı olur. Önemli bir mineral olan kalsiyum sağlar. Deniz suyunda ve mineral yataklarında bulunan doğal bir bileşiktir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "other",
        categoryTr: "Diğer",
    },
    E516: {
        code: "E516",
        name: "Calcium Sulfate (Gypsum)",
        nameTr: "Kalsiyum Sülfat (Alçı)",
        risk: "SAFE",
        reason: "Calcium Sulfate is a natural mineral used for thousands of years in tofu production. It's also used as a flour treatment and dough conditioner. It provides calcium and is completely inert in the body. It's the same mineral used to make plaster of Paris.",
        reasonTr: "Kalsiyum Sülfat, binlerce yıldır tofu üretiminde kullanılan doğal bir mineraldir. Ayrıca un işleme ve hamur düzenleyici olarak kullanılır. Kalsiyum sağlar ve vücutta tamamen inerttir. Alçı yapımında kullanılan aynı mineraldir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "other",
        categoryTr: "Diğer",
    },
    E903: {
        code: "E903",
        name: "Carnauba Wax",
        nameTr: "Karnauba Mumu",
        risk: "SAFE",
        reason: "Carnauba Wax is a natural wax from Brazilian palm leaves. It's the hardest natural wax and is used to give a shiny coating to candies, fruits, and pills. It passes through the body undigested and is completely safe. Also used in car polish and cosmetics.",
        reasonTr: "Karnauba Mumu, Brezilya palmiye yapraklarından elde edilen doğal bir mumdur. En sert doğal mumdur ve şekerlemelere, meyvelere ve hapları parlak kaplama vermek için kullanılır. Vücuttan sindirilmeden geçer ve tamamen güvenlidir. Ayrıca araba cilası ve kozmetikte kullanılır.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "glazing_agent",
        categoryTr: "Parlatıcı",
    },
    E901: {
        code: "E901",
        name: "Beeswax",
        nameTr: "Balmumu",
        risk: "SAFE",
        reason: "Beeswax is a natural wax produced by honey bees. It's been used for thousands of years in food, cosmetics, and candles. It provides a protective coating and shiny appearance to candies and fruits. Note: Not suitable for strict vegans as it's an animal product.",
        reasonTr: "Balmumu, bal arıları tarafından üretilen doğal bir mumdur. Binlerce yıldır gıda, kozmetik ve mumlarda kullanılmaktadır. Şekerleme ve meyvelere koruyucu kaplama ve parlak görünüm sağlar. Not: Hayvansal ürün olduğu için katı veganlar için uygun değildir.",
        euStatus: "ALLOWED",
        fdaStatus: "GRAS",
        category: "glazing_agent",
        categoryTr: "Parlatıcı",
    },
};

// NOVA Grupları

export type NovaGroup = 1 | 2 | 3 | 4;

export interface NovaInfo {
    group: NovaGroup;
    label: string;
    labelTr: string;
    description: string;
    descriptionTr: string;
    color: string;
    icon: string;
    examples: string[];
    examplesTr: string[];
    healthTips: string[];
    healthTipsTr: string[];
}

export const NOVA_GROUPS: Record<NovaGroup, NovaInfo> = {
    1: {
        group: 1,
        label: "Unprocessed or Minimally Processed",
        labelTr: "İşlenmemiş veya Az İşlenmiş",
        description: "Fresh, whole foods that have been altered only by removal of inedible parts, drying, crushing, grinding, filtering, roasting, boiling, pasteurization, refrigeration, freezing, or fermentation. No added salt, sugar, oils, or other substances.",
        descriptionTr: "Yalnızca yenmeyen kısımların çıkarılması, kurutma, ezme, öğütme, filtreleme, kavurma, haşlama, pastörizasyon, soğutma, dondurma veya fermantasyon ile değiştirilmiş taze, bütün gıdalar. Tuz, şeker, yağ veya diğer maddeler eklenmemiştir.",
        color: "#22C55E",
        icon: "leaf",
        examples: ["Fresh fruits and vegetables", "Eggs", "Fresh meat and fish", "Milk", "Plain nuts and seeds", "Legumes", "Fresh herbs", "Water"],
        examplesTr: ["Taze meyve ve sebzeler", "Yumurta", "Taze et ve balık", "Süt", "Sade kuruyemiş ve tohumlar", "Baklagiller", "Taze otlar", "Su"],
        healthTips: ["These foods should form the basis of your diet", "Rich in natural nutrients and fiber", "No artificial additives", "Support overall health and disease prevention"],
        healthTipsTr: ["Bu gıdalar diyetinizin temelini oluşturmalıdır", "Doğal besin maddeleri ve lif açısından zengin", "Yapay katkı maddesi yok", "Genel sağlığı ve hastalık önlemeyi destekler"],
    },
    2: {
        group: 2,
        label: "Processed Culinary Ingredients",
        labelTr: "İşlenmiş Mutfak Malzemeleri",
        description: "Substances obtained from Group 1 foods or from nature by processes like pressing, refining, grinding, or milling. Used in home cooking to prepare, season, and cook Group 1 foods. Rarely consumed alone.",
        descriptionTr: "Presleme, rafine etme, öğütme veya değirmencilik gibi işlemlerle Grup 1 gıdalarından veya doğadan elde edilen maddeler. Grup 1 gıdaları hazırlamak, tatlandırmak ve pişirmek için ev yemeklerinde kullanılır. Nadiren tek başına tüketilir.",
        color: "#84CC16",
        icon: "nutrition",
        examples: ["Olive oil and other vegetable oils", "Butter", "Sugar and honey", "Salt", "Flour", "Pasta (plain)", "Vinegar", "Cream"],
        examplesTr: ["Zeytinyağı ve diğer bitkisel yağlar", "Tereyağı", "Şeker ve bal", "Tuz", "Un", "Makarna (sade)", "Sirke", "Krema"],
        healthTips: ["Use in moderation to enhance Group 1 foods", "Choose high-quality versions when possible", "Extra virgin olive oil over refined oils", "These are cooking tools, not main foods"],
        healthTipsTr: ["Grup 1 gıdaları geliştirmek için ölçülü kullanın", "Mümkün olduğunda yüksek kaliteli versiyonları tercih edin", "Rafine yağlar yerine sızma zeytinyağı", "Bunlar ana gıdalar değil, pişirme araçlarıdır"],
    },
    3: {
        group: 3,
        label: "Processed Foods",
        labelTr: "İşlenmiş Gıdalar",
        description: "Products made by adding Group 2 ingredients to Group 1 foods using preservation methods like canning, bottling, or non-alcoholic fermentation. Usually made with few ingredients and recognizable as modified versions of the original foods.",
        descriptionTr: "Konserveleme, şişeleme veya alkolsüz fermantasyon gibi koruma yöntemleri kullanılarak Grup 1 gıdalarına Grup 2 malzemeleri eklenerek yapılan ürünler. Genellikle az malzeme ile yapılır ve orijinal gıdaların değiştirilmiş versiyonları olarak tanınabilir.",
        color: "#EAB308",
        icon: "cube",
        examples: ["Canned vegetables and legumes", "Canned fish", "Cheese", "Freshly made bread", "Salted or cured meats", "Fruits in syrup", "Pickles"],
        examplesTr: ["Konserve sebzeler ve baklagiller", "Konserve balık", "Peynir", "Taze yapılmış ekmek", "Tuzlanmış veya kürlenmiş etler", "Şuruplu meyveler", "Turşular"],
        healthTips: ["Can be part of a healthy diet in moderation", "Watch sodium content in canned goods", "Check labels for added sugars", "Choose versions with fewer additives"],
        healthTipsTr: ["Ölçülü tüketildiğinde sağlıklı diyetin parçası olabilir", "Konservelerde sodyum içeriğine dikkat edin", "Eklenen şekerler için etiketleri kontrol edin", "Daha az katkı maddesi içeren versiyonları tercih edin"],
    },
    4: {
        group: 4,
        label: "Ultra-Processed Foods",
        labelTr: "Aşırı İşlenmiş Gıdalar",
        description: "Industrial formulations made mostly or entirely from substances derived from foods and additives, with little or no intact Group 1 foods. Often contain ingredients not used in home cooking like high-fructose corn syrup, hydrogenated oils, protein isolates, and many additives.",
        descriptionTr:
            "Çoğunlukla veya tamamen gıdalardan elde edilen maddelerden ve katkı maddelerinden yapılan, çok az veya hiç bozulmamış Grup 1 gıda içermeyen endüstriyel formülasyonlar. Genellikle yüksek fruktozlu mısır şurubu, hidrojenize yağlar, protein izolatları ve birçok katkı maddesi gibi ev yemeklerinde kullanılmayan içerikler içerir.",
        color: "#DC2626",
        icon: "warning",
        examples: ["Soft drinks and energy drinks", "Packaged snacks (chips, cookies)", "Instant noodles", "Processed meats (hot dogs, nuggets)", "Ice cream (most brands)", "Breakfast cereals", "Fast food", "Margarine"],
        examplesTr: ["Meşrubatlar ve enerji içecekleri", "Paketli atıştırmalıklar (cips, kurabiye)", "Hazır erişte", "İşlenmiş etler (sosisli, nugget)", "Dondurma (çoğu marka)", "Kahvaltılık gevrekler", "Fast food", "Margarin"],
        healthTips: ["Limit consumption as much as possible", "Associated with obesity, diabetes, and heart disease", "Often high in sugar, salt, and unhealthy fats", "Designed to be hyper-palatable and addictive", "Replace with Group 1-3 alternatives when possible"],
        healthTipsTr: ["Tüketimi mümkün olduğunca sınırlayın", "Obezite, diyabet ve kalp hastalığı ile ilişkili", "Genellikle şeker, tuz ve sağlıksız yağlar açısından yüksek", "Aşırı lezzetli ve bağımlılık yapıcı olacak şekilde tasarlanmış", "Mümkün olduğunda Grup 1-3 alternatifleriyle değiştirin"],
    },
};

// Helper Functions

export function getAdditiveInfo(code: string): AdditiveInfo | null {
    const normalized = code.toUpperCase().replace(/\s/g, "");
    return ADDITIVE_DATABASE[normalized] || null;
}

export function getAllAdditives(): AdditiveInfo[] {
    return Object.values(ADDITIVE_DATABASE);
}

export function getAdditivesByRisk(risk: AdditiveRisk): AdditiveInfo[] {
    return Object.values(ADDITIVE_DATABASE).filter((a) => a.risk === risk);
}

export function getAdditivesByCategory(category: AdditiveInfo["category"]): AdditiveInfo[] {
    return Object.values(ADDITIVE_DATABASE).filter((a) => a.category === category);
}

export function searchAdditives(query: string): AdditiveInfo[] {
    const q = query.toLowerCase();
    return Object.values(ADDITIVE_DATABASE).filter((a) => a.code.toLowerCase().includes(q) || a.name.toLowerCase().includes(q) || a.nameTr.toLowerCase().includes(q));
}

export function getNovaInfo(group: NovaGroup): NovaInfo {
    return NOVA_GROUPS[group];
}

export function getAllCategories(): { key: AdditiveInfo["category"]; label: string; labelTr: string }[] {
    return [
        { key: "colorant", label: "Colorants", labelTr: "Renklendiriciler" },
        { key: "preservative", label: "Preservatives", labelTr: "Koruyucular" },
        { key: "antioxidant", label: "Antioxidants", labelTr: "Antioksidanlar" },
        { key: "sweetener", label: "Sweeteners", labelTr: "Tatlandırıcılar" },
        { key: "emulsifier", label: "Emulsifiers", labelTr: "Emülgatörler" },
        { key: "thickener", label: "Thickeners", labelTr: "Kıvam Arttırıcılar" },
        { key: "acidity_regulator", label: "Acidity Regulators", labelTr: "Asitlik Düzenleyiciler" },
        { key: "flavor_enhancer", label: "Flavor Enhancers", labelTr: "Lezzet Arttırıcılar" },
        { key: "raising_agent", label: "Raising Agents", labelTr: "Kabartıcılar" },
        { key: "glazing_agent", label: "Glazing Agents", labelTr: "Parlatıcılar" },
        { key: "other", label: "Other", labelTr: "Diğer" },
    ];
}
