export type DietType = "VEGAN" | "VEGETARIAN" | "PESCATARIAN" | "KETO" | "LOW_CARB" | "PALEO" | "WHOLE30" | "MEDITERRANEAN" | "DUKAN" | "ATKINS" | "GLUTEN_FREE" | "LACTOSE_FREE" | "DAIRY_FREE" | "SUGAR_FREE" | "LOW_SODIUM" | "HALAL" | "KOSHER" | "RAW_FOOD" | "FODMAP";

export interface DietDefinition {
    type: DietType;
    name: string;
    nameTr: string;
    description: string;
    descriptionTr: string;
    forbiddenKeywords: string[];
    severity: "strict" | "moderate";
}

export const DIET_DEFINITIONS: Record<DietType, DietDefinition> = {
    VEGAN: {
        type: "VEGAN",
        name: "Vegan",
        nameTr: "Vegan",
        description: "No animal products",
        descriptionTr: "Hiçbir hayvansal ürün yok",
        forbiddenKeywords: [
            "milk",
            "cream",
            "butter",
            "cheese",
            "yogurt",
            "whey",
            "casein",
            "lactose",
            "ghee",
            "dairy",
            "milk powder",
            "milk solids",
            "buttermilk",
            "sour cream",
            "ice cream",
            "condensed milk",
            "evaporated milk",
            "egg",
            "albumin",
            "lysozyme",
            "mayonnaise",
            "meringue",
            "ovalbumin",
            "meat",
            "beef",
            "pork",
            "chicken",
            "turkey",
            "lamb",
            "veal",
            "bacon",
            "ham",
            "sausage",
            "salami",
            "pepperoni",
            "lard",
            "tallow",
            "gelatin",
            "collagen",
            "bone broth",
            "meat extract",
            "animal fat",
            "fish",
            "salmon",
            "tuna",
            "shrimp",
            "prawn",
            "crab",
            "lobster",
            "oyster",
            "mussel",
            "squid",
            "anchovy",
            "sardine",
            "fish sauce",
            "fish oil",
            "omega-3 fish",
            "isinglass",
            "honey",
            "beeswax",
            "royal jelly",
            "propolis",
            "carmine",
            "cochineal",
            "shellac",
            "lanolin",
            "vitamin d3",
        ],
        severity: "strict",
    },

    VEGETARIAN: {
        type: "VEGETARIAN",
        name: "Vegetarian",
        nameTr: "Vejetaryen",
        description: "No meat or fish",
        descriptionTr: "Et ve balık yok",
        forbiddenKeywords: [
            "meat",
            "beef",
            "pork",
            "chicken",
            "turkey",
            "lamb",
            "veal",
            "bacon",
            "ham",
            "sausage",
            "salami",
            "pepperoni",
            "lard",
            "tallow",
            "gelatin",
            "collagen",
            "bone broth",
            "meat extract",
            "animal fat",
            "fish",
            "salmon",
            "tuna",
            "shrimp",
            "prawn",
            "crab",
            "lobster",
            "anchovy",
            "sardine",
            "fish sauce",
            "fish oil",
            "isinglass",
        ],
        severity: "strict",
    },

    PESCATARIAN: {
        type: "PESCATARIAN",
        name: "Pescatarian",
        nameTr: "Pesketaryen",
        description: "No meat, fish allowed",
        descriptionTr: "Et yok, balık serbest",
        forbiddenKeywords: ["meat", "beef", "pork", "chicken", "turkey", "lamb", "veal", "bacon", "ham", "sausage", "salami", "pepperoni", "lard", "tallow", "bone broth", "meat extract"],
        severity: "strict",
    },

    KETO: {
        type: "KETO",
        name: "Ketogenic",
        nameTr: "Ketojenik",
        description: "Very low carb, high fat",
        descriptionTr: "Çok düşük karbonhidrat, yüksek yağ",
        forbiddenKeywords: [
            "sugar",
            "sucrose",
            "glucose",
            "fructose",
            "dextrose",
            "maltose",
            "corn syrup",
            "high fructose corn syrup",
            "agave",
            "maple syrup",
            "honey",
            "molasses",
            "cane sugar",
            "brown sugar",
            "powdered sugar",
            "invert sugar",
            "starch",
            "corn starch",
            "potato starch",
            "modified starch",
            "wheat starch",
            "rice starch",
            "tapioca starch",
            "wheat",
            "flour",
            "bread",
            "pasta",
            "rice",
            "oat",
            "barley",
            "rye",
            "corn",
            "cornmeal",
            "cereal",
            "breadcrumb",
            "bean",
            "lentil",
            "chickpea",
            "pea",
            "potato",
            "sweet potato",
        ],
        severity: "strict",
    },

    LOW_CARB: {
        type: "LOW_CARB",
        name: "Low Carb",
        nameTr: "Düşük Karbonhidrat",
        description: "Reduced carbohydrate intake",
        descriptionTr: "Azaltılmış karbonhidrat alımı",
        forbiddenKeywords: ["sugar", "corn syrup", "high fructose corn syrup", "glucose syrup", "dextrose", "maltodextrin", "starch", "modified starch"],
        severity: "moderate",
    },

    ATKINS: {
        type: "ATKINS",
        name: "Atkins",
        nameTr: "Atkins",
        description: "Low carb, high protein",
        descriptionTr: "Düşük karbonhidrat, yüksek protein",
        forbiddenKeywords: ["sugar", "sucrose", "corn syrup", "high fructose corn syrup", "wheat", "flour", "bread", "pasta", "rice", "potato", "corn", "starch"],
        severity: "strict",
    },

    DUKAN: {
        type: "DUKAN",
        name: "Dukan",
        nameTr: "Dukan",
        description: "High protein, low carb/fat phases",
        descriptionTr: "Yüksek protein, aşamalı karbonhidrat/yağ",
        forbiddenKeywords: ["sugar", "corn syrup", "starch", "wheat", "flour", "bread", "pasta", "rice", "potato", "oil", "butter", "cream"],
        severity: "moderate",
    },

    PALEO: {
        type: "PALEO",
        name: "Paleo",
        nameTr: "Paleo",
        description: "No grains, dairy, legumes, processed",
        descriptionTr: "Tahıl, süt ürünleri, baklagiller, işlenmiş gıda yok",
        forbiddenKeywords: [
            // Tahıllar
            "wheat",
            "flour",
            "bread",
            "pasta",
            "rice",
            "oat",
            "barley",
            "rye",
            "corn",
            "cereal",
            // Süt ürünleri
            "milk",
            "cream",
            "butter",
            "cheese",
            "yogurt",
            "whey",
            "casein",
            "lactose",
            "bean",
            "lentil",
            "chickpea",
            "pea",
            "peanut",
            "soy",
            "soybean",
            "tofu",
            "sugar",
            "corn syrup",
            "vegetable oil",
            "canola oil",
            "soybean oil",
            "margarine",
        ],
        severity: "strict",
    },

    WHOLE30: {
        type: "WHOLE30",
        name: "Whole30",
        nameTr: "Whole30",
        description: "30-day elimination diet",
        descriptionTr: "30 günlük eliminasyon diyeti",
        forbiddenKeywords: [
            "sugar",
            "sweetener",
            "honey",
            "maple syrup",
            "agave",
            "stevia",
            "xylitol",
            "erythritol",
            "alcohol",
            "wine",
            "beer",
            "wheat",
            "flour",
            "bread",
            "pasta",
            "rice",
            "oat",
            "corn",
            "bean",
            "lentil",
            "chickpea",
            "peanut",
            "soy",
            "milk",
            "cream",
            "butter",
            "cheese",
            "yogurt",
            "whey",
            "carrageenan",
            "msg",
            "sulfite",
        ],
        severity: "strict",
    },

    MEDITERRANEAN: {
        type: "MEDITERRANEAN",
        name: "Mediterranean",
        nameTr: "Akdeniz",
        description: "Balanced, olive oil, fish, vegetables",
        descriptionTr: "Dengeli, zeytinyağı, balık, sebze ağırlıklı",
        forbiddenKeywords: ["high fructose corn syrup", "hydrogenated", "trans fat", "margarine", "artificial"],
        severity: "moderate",
    },

    RAW_FOOD: {
        type: "RAW_FOOD",
        name: "Raw Food",
        nameTr: "Çiğ Beslenme",
        description: "Uncooked, unprocessed foods",
        descriptionTr: "Pişirilmemiş, işlenmemiş gıdalar",
        forbiddenKeywords: ["cooked", "roasted", "fried", "baked", "pasteurized", "canned", "processed"],
        severity: "moderate",
    },

    GLUTEN_FREE: {
        type: "GLUTEN_FREE",
        name: "Gluten Free",
        nameTr: "Glutensiz",
        description: "No gluten-containing grains",
        descriptionTr: "Gluten içeren tahıllar yok",
        forbiddenKeywords: ["gluten", "wheat", "barley", "rye", "triticale", "spelt", "kamut", "farina", "semolina", "durum", "bulgur", "couscous", "seitan", "wheat starch", "wheat flour", "bread flour", "all-purpose flour", "malt", "malt extract", "malt vinegar", "brewer's yeast"],
        severity: "strict",
    },

    LACTOSE_FREE: {
        type: "LACTOSE_FREE",
        name: "Lactose Free",
        nameTr: "Laktozsuz",
        description: "No lactose (milk sugar)",
        descriptionTr: "Laktoz (süt şekeri) yok",
        forbiddenKeywords: ["lactose", "milk", "cream", "butter", "cheese", "yogurt", "whey", "milk powder", "milk solids", "buttermilk", "sour cream", "ice cream", "condensed milk", "evaporated milk"],
        severity: "strict",
    },

    DAIRY_FREE: {
        type: "DAIRY_FREE",
        name: "Dairy Free",
        nameTr: "Süt Ürünsüz",
        description: "No dairy products",
        descriptionTr: "Süt ürünleri yok",
        forbiddenKeywords: ["milk", "cream", "butter", "cheese", "yogurt", "whey", "casein", "lactose", "ghee", "dairy", "milk powder", "milk solids", "buttermilk", "sour cream", "ice cream", "condensed milk", "evaporated milk"],
        severity: "strict",
    },

    SUGAR_FREE: {
        type: "SUGAR_FREE",
        name: "Sugar Free",
        nameTr: "Şekersiz",
        description: "No added sugars",
        descriptionTr: "Eklenen şeker yok",
        forbiddenKeywords: [
            "sugar",
            "sucrose",
            "glucose",
            "fructose",
            "dextrose",
            "maltose",
            "corn syrup",
            "high fructose corn syrup",
            "agave",
            "maple syrup",
            "honey",
            "molasses",
            "cane sugar",
            "brown sugar",
            "powdered sugar",
            "invert sugar",
            "glucose syrup",
            "golden syrup",
            "treacle",
            "caramel",
            "muscovado",
            "turbinado",
            "demerara",
        ],
        severity: "strict",
    },

    LOW_SODIUM: {
        type: "LOW_SODIUM",
        name: "Low Sodium",
        nameTr: "Az Tuzlu",
        description: "Reduced sodium intake",
        descriptionTr: "Azaltılmış sodyum alımı",
        forbiddenKeywords: ["salt", "sodium", "msg", "monosodium glutamate", "sodium chloride", "sodium nitrate", "sodium nitrite", "sodium benzoate", "sodium phosphate", "baking soda", "soy sauce"],
        severity: "moderate",
    },

    FODMAP: {
        type: "FODMAP",
        name: "Low FODMAP",
        nameTr: "Düşük FODMAP",
        description: "For IBS - limited fermentable carbs",
        descriptionTr: "IBS için - fermente karbonhidratlar sınırlı",
        forbiddenKeywords: [
            "garlic",
            "onion",
            "wheat",
            "rye",
            "barley",
            "honey",
            "agave",
            "high fructose corn syrup",
            "sorbitol",
            "mannitol",
            "xylitol",
            "maltitol",
            "isomalt",
            "inulin",
            "fructooligosaccharide",
            "chicory root",
            "apple",
            "pear",
            "mango",
            "watermelon",
            "milk",
            "cream",
            "yogurt",
            "ice cream",
            "soft cheese",
        ],
        severity: "strict",
    },

    HALAL: {
        type: "HALAL",
        name: "Halal",
        nameTr: "Helal",
        description: "Islamic dietary laws",
        descriptionTr: "İslami beslenme kuralları",
        forbiddenKeywords: ["pork", "ham", "bacon", "lard", "gelatin", "pepperoni", "salami", "prosciutto", "pancetta", "alcohol", "wine", "beer", "rum", "brandy", "whiskey", "vodka", "liqueur", "wine vinegar", "carmine", "cochineal"],
        severity: "strict",
    },

    KOSHER: {
        type: "KOSHER",
        name: "Kosher",
        nameTr: "Koşer",
        description: "Jewish dietary laws",
        descriptionTr: "Yahudi beslenme kuralları",
        forbiddenKeywords: ["pork", "ham", "bacon", "lard", "shellfish", "shrimp", "crab", "lobster", "oyster", "mussel", "clam", "scallop"],
        severity: "strict",
    },
};

export function getDietDefinition(type: DietType): DietDefinition {
    return DIET_DEFINITIONS[type];
}

export function getAllDietTypes(): DietType[] {
    return Object.keys(DIET_DEFINITIONS) as DietType[];
}

export function checkDietCompliance(ingredients: string[], dietType: DietType): { isCompliant: boolean; violations: string[] } {
    const diet = DIET_DEFINITIONS[dietType];
    const violations: string[] = [];

    const normalizedIngredients = ingredients.map((i) => i.toLowerCase());

    for (const keyword of diet.forbiddenKeywords) {
        const keywordLower = keyword.toLowerCase();
        for (const ingredient of normalizedIngredients) {
            if (ingredient.includes(keywordLower)) {
                violations.push(keyword);
                break;
            }
        }
    }

    return {
        isCompliant: violations.length === 0,
        violations: [...new Set(violations)],
    };
}
